branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Quick Pre-merge Check"
      required_pull_request_reviews:
        required_approving_review_count: 0
      enforce_admins: false
      restrictions: null 