version: '3.8'

services:
  websocket-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=test
    volumes:
      - ./tests:/app/tests
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3 