[tool.poetry]
name = "rag-aether"
version = "0.1.0"
description = "RAG system using Anthropic's Claude"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
anthropic = ">=0.41.0,<0.42.0"
jupyter = ">=1.0.0,<2.0.0"
langchain = ">=0.3.14,<0.4.0"
langchain-anthropic = ">=0.3.1,<0.4.0"
langchain-community = ">=0.3.14,<0.4.0"
langchain-core = ">=0.3.29,<0.4.0"
python-dotenv = ">=1.0.1,<2.0.0"
sentence-transformers = ">=2.5.1,<3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 