[tool.poetry]
name = "rag-aether"
version = "0.1.0"
description = "RAG system for Aether chat features"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
langchain = "^0.1.0"
langchain-openai = "^0.0.2.post1"
langchain-community = "^0.0.12"
sentence-transformers = "^2.5.1"
python-dotenv = "^1.0.0"
openai = "^1.8.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
options.system-site-packages = true 