[tool.poetry]
name = "aether-testing"
version = "0.1.0"
description = "Testing infrastructure for Aether"
authors = ["Aether Team"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.115.6"
torch = "^2.1.0"
numpy = "^1.24.0"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pytest-asyncio = "^0.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
