[tool.poetry]
name = "rag-aether"
version = "0.1.0"
description = "Advanced RAG system with flow protection"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
sentence-transformers = "^2.2.2"
faiss-cpu = "^1.7.4"
numpy = "^1.24.0"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
hypothesis = "^6.75.3"
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short --asyncio-mode=auto"
markers = [
    "asyncio: mark test as async/await test",
    "slow: mark test as slow running",
    "integration: mark test as integration test"
] 