AWSTemplateFormatVersion: '2010-09-09'
Description: 'Aether Monitoring Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues: [production, staging]
    Description: Environment name

  AlertEmail:
    Type: String
    Description: Email address for alerts

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # SNS Topic for Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${AWS::StackName}-alerts
      TopicName: !Sub ${AWS::StackName}-alerts

  AlertTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref AlertTopic
      Endpoint: !Ref AlertEmail

  # CloudWatch Dashboard
  MainDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${AWS::StackName}-main
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", "ClusterName", "${AWS::StackName}-cluster"],
                  [".", "MemoryUtilization", ".", "."]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ECS Cluster Metrics"
              }
            },
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/ElastiCache", "CPUUtilization", "CacheClusterId", "${AWS::StackName}-redis"],
                  [".", "SwapUsage", ".", "."],
                  [".", "DatabaseMemoryUsagePercentage", ".", "."]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Redis Metrics"
              }
            },
            {
              "type": "log",
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/ecs/aether-backend' | fields @timestamp, @message\n| sort @timestamp desc\n| limit 100",
                "region": "${AWS::Region}",
                "title": "Application Logs",
                "view": "table"
              }
            }
          ]
        }

  # ECS Alarms
  ECSCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: ECS CPU utilization above 80%
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      AlarmActions: [!Ref AlertTopic]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Sub ${AWS::StackName}-cluster

  ECSMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: ECS Memory utilization above 80%
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      AlarmActions: [!Ref AlertTopic]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Sub ${AWS::StackName}-cluster

  # Log Groups
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}-backend
      RetentionInDays: !If [IsProduction, 30, 7]

  RedisLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /elasticache/${AWS::StackName}-redis
      RetentionInDays: !If [IsProduction, 30, 7]

  # Log Metric Filters
  ErrorLogMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref ApplicationLogGroup
      FilterPattern: ERROR
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: !Sub ${AWS::StackName}/Logs
          MetricName: ErrorCount

  ErrorLogAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: High number of application errors
      MetricName: ErrorCount
      Namespace: !Sub ${AWS::StackName}/Logs
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !If [IsProduction, 10, 50]
      AlarmActions: [!Ref AlertTopic]
      ComparisonOperator: GreaterThanThreshold

Outputs:
  AlertTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${AWS::StackName}-alert-topic-arn

  DashboardURL:
    Description: URL of the CloudWatch Dashboard
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MainDashboard}
    Export:
      Name: !Sub ${AWS::StackName}-dashboard-url 