AWSTemplateFormatVersion: '2010-09-09'
Description: 'Aether Redis Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues: [production, staging]
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where Redis will be deployed

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for Redis cluster (minimum 2 for production)

  ContainerSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID of the ECS containers

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # Redis Security Group
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref ContainerSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-redis-sg
        - Key: Environment
          Value: !Ref Environment

  # Redis Subnet Group
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis cluster
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-redis-subnet-group
        - Key: Environment
          Value: !Ref Environment

  # Redis Parameter Group
  RedisParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis7
      Description: Parameter group for Redis cluster
      Properties:
        maxmemory-policy: volatile-lru
        maxmemory-samples: 10
        activedefrag: yes
        # Optimized for RAG caching
        maxmemory-percent: 75
        hash-max-ziplist-entries: 512
        hash-max-ziplist-value: 64
        zset-max-ziplist-entries: 128
        zset-max-ziplist-value: 64
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-redis-params
        - Key: Environment
          Value: !Ref Environment

  # Redis Replication Group (for production multi-AZ)
  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub ${AWS::StackName}-redis
      ReplicationGroupDescription: Redis cluster for Aether
      Engine: redis
      EngineVersion: '7.0'
      CacheNodeType: !If [IsProduction, cache.t4g.small, cache.t4g.micro]
      NumCacheClusters: !If [IsProduction, 2, 1]
      AutomaticFailoverEnabled: !If [IsProduction, true, false]
      MultiAZEnabled: !If [IsProduction, true, false]
      CacheParameterGroupName: !Ref RedisParameterGroup
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds: 
        - !Ref RedisSecurityGroup
      Port: 6379
      PreferredMaintenanceWindow: sun:05:00-sun:09:00
      SnapshotRetentionLimit: !If [IsProduction, 7, 1]
      SnapshotWindow: 05:00-09:00
      TransitEncryptionEnabled: true
      AtRestEncryptionEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-redis
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Alarms
  CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-redis-cpu
      AlarmDescription: Redis CPU utilization
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 75
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${RedisReplicationGroup.MemberClusters}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-redis-cpu-alarm
        - Key: Environment
          Value: !Ref Environment

  SwapUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-redis-swap
      AlarmDescription: Redis swap usage
      MetricName: SwapUsage
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 50000000  # 50MB
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${RedisReplicationGroup.MemberClusters}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-redis-swap-alarm
        - Key: Environment
          Value: !Ref Environment

Outputs:
  RedisEndpoint:
    Description: Redis primary endpoint
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address

  RedisPort:
    Description: Redis port
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port

  RedisSecurityGroupId:
    Description: Redis security group ID
    Value: !Ref RedisSecurityGroup 