name: Pre-merge Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  quick-check:
    name: Quick Pre-merge Check
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction || echo "::warning::Some dependencies failed to install"
          cd frontend && npm install || echo "::warning::Some npm packages failed to install"
          
      - name: Style suggestions
        continue-on-error: true
        run: |
          poetry run black --check src || echo "::warning::Code style issues found but not blocking"
          cd frontend && npm run lint -- --max-warnings 25 || echo "::warning::Lint issues found but not blocking"
          
      - name: Critical tests
        id: critical
        run: |
          poetry run pytest tests/unit -v --durations=3 -k "not slow" || echo "::error::Critical tests failed"
          cd frontend && npm run test:critical || echo "::error::Critical frontend tests failed"

      - name: Basic dependency check
        continue-on-error: true
        run: |
          poetry check || echo "::warning::Poetry check found issues"
          
      - name: Status Check
        if: always()
        run: |
          if [ "${{ steps.critical.outcome }}" = "failure" ]; then
            echo "::error::Critical tests failed - please fix before merging"
            exit 1
          fi
          echo "::notice::Checks complete - non-critical issues were found but merge is allowed" 